#!/usr/bin/python
def rm_black(input_im, output_im):
    import cv2
    src = cv2.imread(input_im, 1)
    tmp = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
    _, alpha = cv2.threshold(tmp, 0, 255, cv2.THRESH_BINARY)
    b, g, r = cv2.split(src)
    rgba = [b, g, r, alpha]
    dst = cv2.merge(rgba, 4)
    cv2.imwrite(output_im, dst)
    assert isinstance(dst, object)
    return dst
